import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import HeroSection from '../components/HeroSection/HeroSection'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Koushil Mankali</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/koushil.jpg" />
        <meta
          name="description"
          content="Koushil Mankali a MERN Stack Web Developer. Interested in working on MERN Stack Technology in building good looking and well performing websites. This is a portfolio of my projects."
        />
        <meta
          name="keywords"
          content="koushil mankali, koushil, HTML, CSS, JavaScript, Node JS, React JS, Next JS, PHP, MySQL, Mongo DB, Web Developer, Hyderabad, Full Stack Developer, JavaScript Developer"
        />
        <meta property="og:type" content="portfolio" />
        <meta property="og:title" content="Koushil Mankali Portfolio" />
        <meta
          property="og:description"
          content="Koushil Mankali a MERN Stack Web Developer. Interested in working on MERN Stack Technology in building good looking and well performing websites. This is a portfolio of my projects. "
        />
        <meta property="og:image" content="/Images/koushil.jpg" />
        <meta property="og:site_name" content="Koushil Mankali" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="eng" />
        <meta name="next-head-count" content="18" />
      </Head>
      <HeroSection />
      
    </div>
  );
}
